import { StyleSheet } from 'react-native';

export const loginFormStyles = StyleSheet.create({
  form:               { width: '100%' },
  errorBox:           { backgroundColor: '#fee2e2', borderRadius: 8, padding: 10, marginBottom: 12 },
  errorText:          { color: '#dc2626', fontSize: 13, fontWeight: '500' },
  label:              { fontSize: 13, fontWeight: '600', color: '#1e293b', marginBottom: 4 },
  roleRow:            { flexDirection: 'row', gap: 8, marginBottom: 14 },
  roleBtn:            { flex: 1, padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#CCCCCC', alignItems: 'center', backgroundColor: '#F8FAFC' },
  roleBtnActive:      { backgroundColor: '#1A3C6E', borderColor: '#1A3C6E' },
  roleBtnText:        { fontSize: 13, color: '#1e293b', fontWeight: '600' },
  roleBtnTextActive:  { color: '#fff' },
  input:              { borderWidth: 1, borderColor: '#CCCCCC', borderRadius: 8, padding: 12, fontSize: 15, color: '#1e293b', backgroundColor: '#FAFAFA', marginBottom: 12 },
  inputDisabled:      { opacity: 0.6 },
  showPasswordRow:    { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  checkbox:           { width: 18, height: 18, borderWidth: 1.5, borderColor: '#CCCCCC', borderRadius: 4, justifyContent: 'center', alignItems: 'center' },
  checkboxChecked:    { backgroundColor: '#1A3C6E', borderColor: '#1A3C6E' },
  checkmark:          { color: '#fff', fontSize: 11, fontWeight: '700' },
  showPasswordLabel:  { fontSize: 13, color: '#64748b' },
  btn:                { backgroundColor: '#1A3C6E', borderRadius: 8, padding: 14, alignItems: 'center' },
  btnDisabled:        { opacity: 0.65 },
  btnText:            { color: '#fff', fontWeight: '700', fontSize: 15 },
});

export const voteFormStyles = StyleSheet.create({
  form:                 { width: '100%' },
  fieldset:             { backgroundColor: '#fff', borderRadius: 10, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: '#E2E8F0' },
  legend:               { fontSize: 15, fontWeight: '700', color: '#1A3C6E', marginBottom: 10 },
  radioGroup:           { gap: 8 },
  radioLabel:           { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#F8FAFC' },
  radioLabelSelected:   { borderColor: '#1A3C6E', backgroundColor: '#EBF5FB' },
  radioCircle:          { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#CCCCCC', justifyContent: 'center', alignItems: 'center' },
  radioCircleSelected:  { borderColor: '#1A3C6E' },
  radioDot:             { width: 10, height: 10, borderRadius: 5, backgroundColor: '#1A3C6E' },
  radioText:            { fontSize: 14, color: '#1e293b', flex: 1 },
  radioTextSelected:    { fontWeight: '600', color: '#1A3C6E' },
  btn:                  { backgroundColor: '#1A3C6E', borderRadius: 8, padding: 14, alignItems: 'center', marginTop: 8 },
  btnDisabled:          { backgroundColor: '#94a3b8' },
  btnText:              { color: '#fff', fontWeight: '700', fontSize: 15 },
  successCard:          { alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 32 },
  successIcon:          { fontSize: 52, marginBottom: 12 },
  successTitle:         { fontSize: 20, fontWeight: '700', color: '#1A3C6E', marginBottom: 8 },
  successSub:           { fontSize: 14, color: '#64748b', textAlign: 'center' },
});
