import { StyleSheet } from 'react-native';
import { colors, font, radius, spacing } from '../theme';

const manageCandidatesStyles = StyleSheet.create({
  page:               { flex: 1, backgroundColor: colors.bgLight },
  successBanner:      { backgroundColor: '#dcfce7', padding: spacing.md, margin: spacing.md, borderRadius: radius.md },
  successText:        { color: colors.success, fontWeight: '600', textAlign: 'center' },
  addBtn:             { backgroundColor: colors.primary, margin: spacing.md, borderRadius: radius.md, padding: 13, alignItems: 'center' },
  addBtnText:         { color: '#fff', fontWeight: '700', fontSize: font.md },
  formCard:           { backgroundColor: colors.cardBg, margin: spacing.md, borderRadius: radius.md, padding: spacing.lg, elevation: 2 },
  formTitle:          { fontSize: font.md, fontWeight: '700', color: colors.primary, marginBottom: spacing.md },
  label:              { fontSize: font.sm, fontWeight: '600', color: colors.textDark, marginBottom: 4 },
  input:              { borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, fontSize: font.base, color: colors.textDark, marginBottom: spacing.md, backgroundColor: '#FAFAFA' },
  posChip:            { paddingHorizontal: 14, paddingVertical: 7, borderRadius: radius.full, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.bgLight },
  posChipActive:      { backgroundColor: colors.primary, borderColor: colors.primary },
  posChipText:        { fontSize: font.sm, color: colors.textMuted, fontWeight: '600' },
  posChipTextActive:  { color: '#fff' },
  btnRow:             { flexDirection: 'row', gap: spacing.sm },
  btn:                { flex: 1, backgroundColor: colors.primary, borderRadius: radius.md, padding: 12, alignItems: 'center' },
  btnText:            { color: '#fff', fontWeight: '700', fontSize: font.base },
  outlineBtn:         { flex: 1, borderWidth: 1, borderColor: colors.primary, borderRadius: radius.md, padding: 12, alignItems: 'center' },
  outlineBtnText:     { color: colors.primary, fontWeight: '600', fontSize: font.base },
  tabsScroll:         { marginHorizontal: spacing.md, marginBottom: spacing.sm },
  tabsRow:            { flexDirection: 'row', gap: spacing.xs, paddingVertical: spacing.sm },
  tab:                { paddingHorizontal: 14, paddingVertical: 7, borderRadius: radius.full, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.bgLight },
  tabActive:          { backgroundColor: colors.primary, borderColor: colors.primary },
  tabText:            { fontSize: font.sm, color: colors.textMuted, fontWeight: '600' },
  tabTextActive:      { color: '#fff' },
  candidateRow:       { backgroundColor: colors.cardBg, marginHorizontal: spacing.md, marginBottom: spacing.sm, borderRadius: radius.md, padding: spacing.md, flexDirection: 'row', alignItems: 'center', elevation: 1 },
  avatar:             { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center', marginRight: spacing.sm },
  avatarText:         { color: '#fff', fontWeight: '700', fontSize: font.lg },
  candidateInfo:      { flex: 1 },
  candidateName:      { fontSize: font.base, fontWeight: '700', color: colors.textDark },
  candidatePos:       { fontSize: font.sm, color: colors.secondary },
  candidateVotes:     { fontSize: font.sm, color: colors.textMuted },
  actions:            { gap: spacing.xs },
  editBtn:            { backgroundColor: colors.accent, borderRadius: radius.sm, paddingHorizontal: 12, paddingVertical: 5, marginBottom: 4 },
  editBtnText:        { color: colors.primary, fontSize: font.sm, fontWeight: '600' },
  deleteBtn:          { backgroundColor: '#fee2e2', borderRadius: radius.sm, paddingHorizontal: 12, paddingVertical: 5 },
  deleteBtnText:      { color: colors.danger, fontSize: font.sm, fontWeight: '600' },
  empty:              { alignItems: 'center', padding: spacing.xl },
  emptyText:          { color: colors.textMuted, fontSize: font.base },
});

export default manageCandidatesStyles;
